config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'contact-me', to: 'messages#new', as: 'new_message'
  post 'contact-me', to: 'messages#create', as: 'create_message'

  resources :home, only: [:index, :show]
  resources :cc, only: [:index, :show]
  resources :dv, only: [:index]
  resources :real_cap, only: [:index]
  resources :dmservices, only: [:index]
  resources :contact, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :body
  validates :name, :email, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cc_controller.rb
class CcController < ApplicationController
  def index

  end

  def show
    
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/dmservices_controller.rb
class DmservicesController < ApplicationController
  def index
    
  end
end

app/controllers/dv_controller.rb
class DvController < ApplicationController

  def index
  
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def show

  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  # def create
  #   message_params = params.require(:message).permit(:name, :email, :body)
  #   @message = Message.new message_params
  #
  #   if @message.valid?
  #     redirect_to new_message_url, notice: "Message received, thanks!"
  #   else
  #     render :new
  #   end
  # end

  def create
    @message = Message.new(message_params)

    if @message.valid?
      MessageMailer.contact_me(@message).deliver_now
      redirect_to new_message_url, notice: "Message received"
    else
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :body)
  end

end

app/controllers/real_cap_controller.rb
class RealCapController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cc_helper.rb
module CcHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/dmservices_helper.rb
module DmservicesHelper
end

app/helpers/dv_helper.rb
module DvHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/real_cap_helper.rb
module RealCapHelper
end

app/views/cc/index.html.erb
<div class="site-header-cc">
  <div class="header-bg-container">
    <div class="cc-info-container">
      <h1 class="cc-info-title">Closed Captioning</h1>
      <div class="cc-info-elements">
        <div class="cc-icon-container">
          <img src="./assets/icons/user-typing.png", class="cc-info-icon user">
          <img src="./assets/icons/keyboard.png", class="cc-info-icon keyboard">
          <img src="./assets/icons/caption.png", class="cc-info-icon caption">
        </div>
        <div class="cc-info-text-container cc">
          <p class="cc-info-text 1">
            Closed captioning is the transcription of both spoken word, as well as the written description of music, sound effects, and other audio cues that are necessary to enjoy a piece of media.
          </p>
          <p class="cc-info-text 2">
            With this service, film, television, promos, and advertisements can be provided to a more inclusive audience, specifically those who are deaf or hard of hearing. When you see white text on black bars, this is closed captioning.
          </p>
          <p class="cc-info-text 3">
            Under the regulations of the CRTC, 100% of broadcasted programs during the day, including advertising, sponsorship messages, and promotional content, must be captioned.
          </p>
        </div>
      </div>
      <div class="subs-info-container">
        <h1 class="subs-info-title"> Subtitles</h1>
        <div class="subs-info-elements">
          <div class="subs-icon-container">
            <img src="./assets/icons/translation.png", class="subs-info-icon translation">
            <img src="./assets/icons/audience.png", class="subs-info-icon audience">
            <img src="./assets/icons/subtitle-filled.png", class="cc-info-icon sub">
          </div>
          <div class="subs-info-text-container">
            <p class="subs-info-text 1">
              Subtitling is the translation of an original script from a piece of media into a secondary language. This is done in order to provide greater accessibility to other language groups, and wider exposure for the media in question.
            </p>
            <p class="subs-info-text 2">
              Unlike closed captioning, sound effects and music are not included in this text. Often, to bring some clarity in hard-to-hear situations, same-language subtitling is provided, too.
            </p>
            <p class="subs-info-text 3">
              Subtitles are also more compatible with HDMI reliant setups than closed captioning, as well as other modern technologies and formats.
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="standards-container">
      <div class="standards-elements">
        <div class="standards-info industry">
          <h2 class="standards-title">Industry Standards</h2>
          <img src="./assets/icons/antenna.png", class="standards-icon antenna">
          <p class="standards-text">
            Onextra provides closed captioning in both Pop On and Roll-Up styles for Canada's largest broadcasters, content producers and distributors.
            EIA-608 or CEA-708 standards and Web captioning exports are available.
            Our services are ideal for:
            Broadcasters, Television Content Producers, Distributors and Web Producers.
          </p>
        </div>
        <div class="standards-info english/french">
          <h2 class="standards-title">Bilingual Services</h2>
          <img src="./assets/icons/bilingual_1.png", class="standards-icon bilingual">
          <p class="standards-text">
            We offer closed captioning in both English and French languages.
            You'll be able to expand your reach to a wider audience in both official languages.
          </p>
        </div>
        <div class="standards-info subtitling">
          <h2 class="standards-title">Subtitling</h2>
          <img src="./assets/icons/subs.png", class="standards-icon subs">
          <p class="standards-text">
            Subtitles offer several valuable benefits.
            Whereas closed captioning will not pass through an HDMI cable, subtitles are ideal for use with modern technologies and formats.
            Subtitling is available in English, French, Spanish and other languages.
            It is a go-to choice for most web based content as well.
            3D subtitles are available for side-by-side and for stereoscopic 3D content.
          </p>
        </div>
        <div class="standards-info dig-media">
          <h2 class="standards-title">Digital Media</h2>
          <img src="./assets/icons/digital_media.png", class="standards-icon dig-media">
          <p class="standards-text">
            With more than 30 years of combined experience in digital media, we make sure your closed captions or subtitles work perfectly on all platforms.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cc/show.html.erb
<div class="cc-info-container-v2">
  <h1 class="cc-info-title-v2">Closed Captioning | Subtitles</h1>
  <div class="cc-info-elements-v2">
    <div class="cc-icon-container-v2">
      <img src="./assets/icons/user-typing.png", class="cc-info-icon user">
      <img src="./assets/icons/keyboard.png", class="cc-info-icon keyboard">
    </div>
    <div class="cc-info-text-container-v2">
      <p class="cc-info-text-v2 1">
        Closed captioning is the transcription of both spoken word, as well as the written description of music, sound effects, and other audio cues that are necessary to enjoy a piece of media.
      </p>
      <p class="cc-info-text-v2 2">
        With this service, film, television, promos, and advertisements can be provided to a more inclusive audience, specifically those who are deaf or hard of hearing. When you see white text on black bars, this is closed captioning.
      </p>
      <p class="cc-info-text-v2 3">
        Under the regulations of the CRTC, 100% of broadcasted programs during the day, including advertising, sponsorship messages, and promotional content, must be captioned.
      </p>
    </div>
  </div>
</div>

app/views/contact/index.html.erb
<h1>Contact#index</h1>
<p>Find me in app/views/contact/index.html.erb</p>

app/views/dv/index.html.erb
<div class="site-header-dv">
  <div class="dv-info-container">
    <h1 class="dv-info-title">Engaging Descriptive Video</h1>

    <p class="dv-info-text">
      Reach wider audiences by incorporating Descriptive Video (DV) into your production.
      Onextra in Toronto, Ontario, offers this service for recorded television shows, feature films for broadcast or for distribution, and Live DV services for live events.
    </p>
  </div>

  <div class="dv-standards-container">
    <div class="dv-standards-elements">
      <div class="dv-standards-info dv">
        <h2 class="dv-standards-title">Descriptive Video</h2>
        <img src="./assets/icons/audio_waves.png" class="dv-icon dv">
        <p class="dv-standards-text">
          Our DV production team creates quality descriptive soundtracks for current television shows, feature films, documentaries and children's shows for major broadcasters and content producers coast-to-coast. Onextra is actively participating in Best Practices Working Group to continually improve and share experience with our industry.
        </p>
      </div>
      <div class="dv-standards-info lv">
        <h2 class="dv-standards-title">Live Description</h2>
        <img src="./assets/icons/audio_speech.png" class="dv-icon lv">
        <p class="dv-standards-text">
          Live Descriptive video services helps people with visual impairments to get the most out of live television broadcasts, such as award shows or The PGA Tour. This new service is currently provided by only few companies, and with more than two years of experience, Onextra is at the forefront of Live DV.
        </p>
      </div>
      <div class="dv-standards-info voice">
        <h2 class="dv-standards-title">Top Voice Talents</h2>
        <img src="./assets/icons/microphone.png" class="dv-icon voice">
        <p class="dv-standards-text">
          By recruiting top voice talents, we ensure your show is highly engaging for people with visual impairments. This is especially important for live broadcasts, which have the potential to attract larger audiences. Through careful research, we hire professional on-air announcers who are specifically chosen to suit your program. Male and female voice talents are available.
        </p>
      </div>
      <div class="dv-standards-info practice">
        <h2 class="dv-standards-title">Best Practices</h2>
        <img src="./assets/icons/sound_on.png" class="dv-icon sound">
        <img src="./assets/icons/audio_mixer.png" class="dv-icon mixer">
        <p class="dv-standards-text">
          As a member of the Described Video Best Practices Working Group, we are at the forefront of the industry. Our professional writers and voice talents describe the most popular TV shows on the air today. Find out why top names in the industry trust us to provide their accessibility services.
        </p>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="site-header-home">
  <div class="onextra-container">
    <div class="onextra-items">
      <a href="/" class="logo">
        <img src="./assets/Onextra_2016  FX with logo 2000dpi.png" class="onextra-logo">
      </a>
      <span class="onextra-title">Media Accessibility Services</span>
      <span class="onextra-description">(Pending Slogan)</span>
    </div>
  </div>

  <div class="about-us-home-container">
    <div class="about-us-items">
      <div class="about-us-icons-container">
        <img src="./assets/icons/subtitles.png", class="about-logo-sub">
        <img src="./assets/icons/cc.png", class="about-logo-cc">
        <img src="./assets/icons/video.png", class="about-logo-video">
      </div>
    </div>
    <div class="about-us-text-container">
      <p class="about-us 1">
        We offer closed captioning, subtitling, and descriptive video services to help you bring your production to more people.
      </p>
      <p class="about-us 2">
        With a proven track record and extensive experience in the industry, we offer accurate, affordable services that you can rely on.
      </p>
    </div>
  </div>

  <!-- <div class="our-clients-container">
    <div class="our-clients-logos">
      <img src="./assets/icons/bell_media_alt-colour.png", class="client-logo-bell">
      <img src="./assets/icons/corus_alt-colour.png", class="client-logo-corus">
      <img src="./assets/icons/shaw_alt-colour.png", class="client-logo-shaw">
      <img src="./assets/icons/vice_alt-colour.png", class="client-logo-vice">
    </div>
  </div> -->

  <a id="contact-me-link-target"></a>
  <div class="social-media-container">
    <div class="social-media-items">
      <div class="social-media-contact-container">
        <div class="social-media-contact-items">
          <h1 class="social-media-contact-title">CONTACT US</h1>
        </div>
        <div class="form-container">
          <form id="form" class="topBefore">
            <input id="name" type="text" placeholder="Name">
            <input id="email" type="text" placeholder="Email">
            <textarea id="message" type="text" placeholder="Message"></textarea>
            <input id="submit" type="submit" value="Submit">
          </form>
        </div>
      </div>
      <div class="social-media-logo-container">
        <img src="./assets/icons/facebook.png" class="social-media-logo facebook">
        <img src="./assets/icons/google-plus.png" class="social-media-logo google">
        <img src="./assets/icons/twitter.png" class="social-media-logo twitter">
        <img src="./assets/icons/linkedin.png" class="social-media-logo linkedin">
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= favicon_link_tag 'onextra_favicon.ico' %>
  <head>
    <title>ONEXTRA</title>
    <!-- <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet"> -->
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav-bar">
      <div class="nav-container">
        <div class="nav-menu">
          <a href="/" class="nav-logo-container">
            <img src="./assets/onextra_short_logo.png" class="onextra-nav-logo">
          </a>
          <%= link_to "Closed Captioning | Subtitling", 'cc#index', class: "nav-items" %>
          <%= link_to "DV | LIVE DV", 'dv#index', class: "nav-items" %>
          <%= link_to "Real-Time Captioning", 'real_cap#index', class: "nav-items" %>
          <%= link_to "Digital Media Services", 'dmservices#index', class: "nav-items" %>
          <%= link_to "Contact", "/#contact-me-link-target", class: "nav-items" %>
        </div>
      </div>
    </div>
    <div class="angle-down arrow">⌄
      <!-- <img src="./assets/icons/down_arrow.png" class="down_arrow"> -->
    </div>


    <%= yield %>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>

    <!-- <div class="wrapper">



      <div class="push"></div>
    </div> -->
    <footer class="footer">&copy; Onextra 2017</footer>

  </body>

  <!-- <footer>
    &copy; Onextra 2017
  </footer> -->

</html>

app/views/messages/new.html.erb
<div class="mailer-container">
  <%= form_for @message, url: create_message_url do |f| %>
  <%= notice %>
  <%= @message.errors.full_messages.join(', ') %>

  <%= f.text_field :name, placeholder: 'Name' %>
  <%= f.email_field :email, placeholder: 'Email' %>
  <%= f.text_area :body, placeholder: 'Message' %>
  <%= f.submit 'Submit' %>
  <% end %>  
</div>

app/views/real_cap/index.html.erb
<div class="site-header-real_cap">
  <div class="real_cap-info-container">
    <h1 class="real_cap-info-title"> Real-Time Captioning</h1>

    <p class="real_cap-info-text">
      Make your broadcast compliant to regulatory requirements, Real-Time captioning services by Onextra Inc.
      Based in Toronto, Ontario, we offer live captioning services throughout Canada to broadcasters and live events.
    </p>
  </div>

  <div class="real_cap-standards-container">
    <div class="real_cap-standards-elements">
      <div class="real_cap-standards-info accuracy">
        <h2 class="real_cap-standards-title">High Accuracy</h2>
        <img src="./assets/icons/broadcast-2.png" class="real_cap-icon broadcast">
        <p class="real_cap-standards-text">
          Our accuracy rate is one of the best in the industry. We work with the best talents in the business, while keeping our prices competitive. Contracts and emergency fill-in rates are available.
        </p>
      </div>
      <div class="real_cap-standards-info live">
        <h2 class="real_cap-standards-title">Live Shows</h2>
        <img src="./assets/icons/announcer.png" class="real_cap-icon announcer">
        <img src="./assets/icons/microphone-2.png" class="real_cap-icon microphone">
        <p class="real_cap-standards-text">
          Reach new audiences from coast to coast by providing closed captions for any broadcast. We specialize in news, sporting events, and live reality shows.
        </p>
      </div>
    </div>
  </div>

</div>